version: '3.8'

# Services
services: 
    # Nginx
    nginx:
        image: nginx:1.19
        ports: 
            - 8081:80
        volumes: 
            - ./src/backend:/var/www/backend
            - ./.docker/nginx/conf.d:/etc/nginx/conf.d
        depends_on: 
            - backend

    # Backend
    backend:
        build: ./src/backend
        working_dir: /var/www/backend
        volumes:
            - ./src/backend:/var/www/backend
        depends_on:
            mysql:
                condition: service_healthy

    # MySQL
    mysql:
        image: mysql:8.0
        volumes: 
            - ./.docker/mysql/conf.d/my.cnf:/etc/mysql/conf.d/my.cnf
            - mysqldata:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: abc123456
            MYSQL_DATABASE: demo
        healthcheck:
            test: mysqladmin ping -h 127.0.0.1 -u root --password=$$MYSQL_ROOT_PASSWORD
            interval: 5s
            retries: 10
        ports:
            - 13306:3306

# Volumes
volumes:
    mysqldata: